kind: pipeline
type: docker
name: default

steps:
- name: Build Server
  image: gcc
  commands:
    - mkdir dist
    - mkdir dist/server
    - cd server
    - make server
    - cd ..
    - cp conf/prod_env.sh dist/server/env.sh

- name: Build Client
  image: emscripten/emsdk
  commands:
    - mkdir dist/client
    - cd client
    - make client
    - cd ..

- name: Clone Proxdeploy
  image: alpine/git
  commands:
    - git clone http://192.168.1.211:3000/jmarlin/proxdeploy.git
    - cd proxdeploy
    - git checkout master
  
- name: Proxdeploy
  image: python
  environment:
    PROX_USER:
      from_secret: prox_user
    PROX_PASS:
      from_secret: prox_pass
    PROX_HOST:
      from_secret: prox_host
    PROX_PUB_KEY:
      from_secret: general_key
    PROX_PRIV_KEY:
      from_secret: general_private_key
  commands:
    - cd proxdeploy  
    - pip3 install -r requirements.txt
    - python3 ./proxdeploy.py .proxconf.yml
